SCREEN_W = 800
SCREEN_H = 600

PLAYER_PATH = "Assets/Characters/Player/Fiery_Imp/"
ENEMY_PATH = "Assets/Characters/Enemies/"

PLAYER_FACTOR = 2
PLAYER_SPEED = 300
PLAYER_JUMPFORCE = -300
PLAYER_OFFSET_X = 9.5 * PLAYER_FACTOR
PLAYER_OFFSET_Y = 13 * PLAYER_FACTOR
PLAYER_OFFSET_W = 20 * PLAYER_FACTOR
PLAYER_OFFSET_H = 10 * PLAYER_FACTOR

ANIMATION_COOLDOWN = 0.08
GRAVITY = 1

R_COLOR = (255, 0, 0)
G_COLOR = (0, 255, 0)
B_COLOR = (0, 0, 255)