SCREEN_W = 800
SCREEN_H = 600

PLAYER_PATH = "Assets/Characters/Player/Fiery_Imp/"
ENEMY_PATH = "Assets/Characters/Enemies/"
MAP_PATH = "maps/"

PLAYER_FACTOR = 2
PLAYER_SPEED = 300
PLAYER_JUMPFORCE = -450
FPS_TARGET = 60.0
PLAYER_OFFSET_X = 9.5 * PLAYER_FACTOR
PLAYER_OFFSET_Y = 13 * PLAYER_FACTOR
PLAYER_OFFSET_W = 20 * PLAYER_FACTOR
PLAYER_OFFSET_H = 10 * PLAYER_FACTOR

BAT_FACTOR = 1.5
FROG_FACTOR = 1.6
SLIME_FACTOR = 1.5
MAP_FACTOR = 2

BAT_FLY_SPEED = 100
FROG_SPEED = 100
SLIME_SPEED = 160

FROG_JUMPFORCE = -300

SLIME_OFFSET_X = 5 * SLIME_FACTOR
SLIME_OFFSET_Y = 14 * SLIME_FACTOR
SLIME_OFFSET_W = 8 * SLIME_FACTOR
SLIME_OFFSET_H = 10 * SLIME_FACTOR

ANIMATION_COOLDOWN = 0.08
GRAVITY = 6
TILE_SIZE = 16 * MAP_FACTOR

AGGRO_W, AGGRO_H = 350, 50

R_COLOR = (255, 0, 0)
G_COLOR = (0, 255, 0)
B_COLOR = (0, 0, 255)